apiVersion: v1
kind: ReplicationController
metadata:
  name: mypod
spec:
    replicas: 5
    template:
      metadata:
         labels:
          app: test
      spec:
        containers:
         - image: nginx
           name: mycont
           ports:
             - containerPort: 80
           livenessProbe:
              exec:
                command:
                   - cd /usr/share/nginx/html
                   - touch home.html
